### ISSUE TITLE
lat/lon getting stored as a strings after moving anchor

### ISSUE THREAD

**Issue by davidsanner** [sbender9/signalk-anchoralarm-plugin#41]
Initially   navigation.anchor.position is stored as numbers (w/o quotes)
{
  "latitude": 37.973971744676,
  "longitude": -122.655220431947,
  "altitude": -3.64
}
But after moving anchor position via webapp the position values are stored as strings
{
  "latitude": "37.984587980821",
  "longitude": "-122.664388656616",
  "altitude": -3.77
}
--------------- btw, the track display on the webapp is great, thx -----

Side issue: in alarm state the audio notifications are sent at such a high rate they collide and stack up having several voicing at the same time.

**Comment by sbender9** [comment]
Yeah, this is a problem. @itemir

**Comment by itemir** [comment]
Hmm, ok, will look into it. Before I make any more changes, can merge [this](https://github.com/sbender9/signalk-anchoralarm-plugin/pull/40) though? My branch is already ahead of master and I need to find a way to rebase it before putting in more fixes.
