### ISSUE TITLE
Add setRodeLength to call after dropAnchor

### ISSUE THREAD

**Issue by sbender9** [sbender9/signalk-anchoralarm-plugin#44]
This would compute the alarm radius based on that instead of gps position.

**Comment by gregsyoung** [comment]
not sure i understand whats proposed here?

**Comment by gregsyoung** [comment]
ability to manually tell the plugin actual rode that you deployed? (ie from chain counter) 

If so, i like this idea, albeit i currently have this as a path in SK (navigation.anchor.rodeDeployed )
 that is populated from my chain counter device.
so question… 
will the program try to overide or change whats already in my above SK path.?

**Comment by sbender9** [comment]
It would not mess your path. 

It would just calculate the alarm radius based on depth, bow height, and rode length.

**Comment by gregsyoung** [comment]
ah ok, the title confused me a little ..

**Comment by gregsyoung** [comment]
these would be better defined as “feature request” (currently you raised them as “issues”)

**Comment by sbender9** [comment]
It's SOP to use issues for feature request.

**Comment by gregsyoung** [comment]
noted 
.. ive seen other github authors get antsy when labelling them “issues” 

haha .. lucky  your not one of them!
