### ISSUE TITLE
Add alarm if setRadius is not called.

### ISSUE THREAD

**Issue by sbender9** [sbender9/signalk-anchoralarm-plugin#45]
This would happen if the user forgets to set the radius after dropAnchor. Make the time user configurable.

**Comment by gregsyoung** [comment]
great idea.
time check could be configurable, 
but an initial default would be 10min. 
(to get past all the normal anchoring shenaningans and get settled, (before yet another alerts goes off)
to do some checks of swing radius, weather conditions etc)
